name: Build macOS MAUI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List installed Xcode versions (optional)
        run: ls /Applications | grep Xcode

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Set up .NET SDK 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore workloads
        run: dotnet workload restore

      - name: Build MacCatalyst project
        run: dotnet build -f net8.0-maccatalyst --configuration Release

      - name: Zip MacCatalyst .app bundle
        run: |
          cd auto_cliker/bin/Release/net8.0-maccatalyst/
          zip -r auto_cliker.app.zip auto_cliker.app

      - name: Upload macOS App Artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: auto_cliker/bin/Release/net8.0-maccatalyst/auto_cliker.app.zip
