name: Build macOS MAUI App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Setup .NET 9 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET Workloads
        run: dotnet workload restore

      - name: Build MacCatalyst project
        run: dotnet build auto_cliker.csproj -f net8.0-maccatalyst --configuration Release

      - name: Archive built .app
        run: |
          cd auto_cliker/bin/Release/net8.0-maccatalyst/
          zip -r auto_cliker.app.zip auto_cliker.app

      - name: Upload .app artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-app
          path: auto_cliker/bin/Release/net8.0-maccatalyst/auto_cliker.app.zip
