name: Build macOS MAUI App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Select Xcode 15.3
        run: sudo xcode-select -s /Applications/Xcode_15.3.app

      - name: Verify Xcode version
        run: xcodebuild -version

      - name: Set up .NET SDK 9
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore .NET workloads
        run: dotnet workload restore

      - name: Build MacCatalyst project
        run: |
          dotnet build auto_cliker.csproj -f net8.0-maccatalyst --configuration Release
          echo "Build output:"
          find . -name "*.app" -o -name "*.dll"

      - name: Find and zip .app
        run: |
          APP_PATH=$(find . -name "auto_cliker.app" | head -1)
          if [ -z "$APP_PATH" ]; then
            echo "::error::.app bundle not found!"
            exit 1
          fi
          cd $(dirname "$APP_PATH")
          zip -r app.zip auto_cliker.app
          ls -lh

      - name: Upload built .app
        uses: actions/upload-artifact@v4
        with:
          name: macos-app
          path: |
            **/app.zip
            **/auto_cliker.app
