name: Build .NET MAUI macOS App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build MAUI macOS app
      run: dotnet publish YourProjectName.csproj -f:net9.0-maccatalyst -c:Release -o:publish-macos

    - name: Commit macOS Build Artifacts
      uses: EndBug/add-and-commit@v9
      with:
        message: "Add macOS build"
        add: "publish-macos"
        new_branch: macos-build-artifacts


