name: Build macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-13

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Select Xcode 15.3
      run: sudo xcode-select -s /Applications/Xcode_15.3.app

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Install MAUI Workload
      run: dotnet workload restore

    - name: Build for MacCatalyst
      run: dotnet build -f net9.0-maccatalyst --configuration Release
